// release-examples/angular/src/app.component.ts
import { Component, computed, inject, signal } from "@angular/core";
import { NovaChatComponent, type ToolDefinition } from "@wp-nova/chat-sdk-angular";
import { DispatchToolRegistration } from "./dispatch-tools.service";

// Switchyard Dispatch — a field-service board that consumes the RELEASED
// @wp-nova/chat-sdk-angular wrapper. State is held in signals so the view stays
// correct under zoneless change detection, including when the agent mutates it
// through a tool handler.

type JobStatus = "Queued" | "En route" | "On site" | "Closed";

interface Job {
    id: string;
    route: string;
    technician: string;
    status: JobStatus;
    priority: "low" | "normal" | "high";
    summary: string;
}

const INITIAL_JOBS: Job[] = [
    {
        id: "SY-318",
        route: "North yard signal heater",
        technician: "Dana Powell",
        status: "En route",
        priority: "high",
        summary: "Heater tripping the breaker on switch 7; bring spare relay.",
    },
    {
        id: "SY-322",
        route: "Cold dock reefer telemetry",
        technician: "Ravi Shah",
        status: "Queued",
        priority: "normal",
        summary: "Telemetry gap before the Spokane departure window.",
    },
    {
        id: "SY-329",
        route: "Track 8 inspection",
        technician: "Lena Ortiz",
        status: "On site",
        priority: "low",
        summary: "Routine overnight inspection; confirm liftgate clearance.",
    },
];

@Component({
    standalone: true,
    selector: "app-root",
    imports: [NovaChatComponent],
    template: `
        <!-- Docs: Angular > Component Mount + Disabling Chat. -->
        <wp-nova-chat-mount [tools]="tools" [enabled]="chatEnabled()" />

        <div class="app-shell">
            <header class="masthead">
                <div>
                    <p class="eyebrow">Switchyard Dispatch</p>
                    <h1>Control desk</h1>
                </div>
                <p class="banner" role="status">{{ banner() }}</p>
            </header>

            @if (!chatEnabled()) {
                <p class="notice">
                    Set <code>VITE_NOVA_PUBLIC_SURFACE_ID</code> in <code>.env</code> to mount the
                    chat launcher.
                </p>
            }

            <!-- data-ai-context is only captured from VISIBLE, in-viewport,
                 non-sensitive elements, so these render as a small context line. -->
            <p class="context">
                <span data-ai-context="currentPageKind">dispatch-board</span>
                <span data-ai-context="activeJobId">{{ activeJob().id }}</span>
            </p>

            <main class="layout">
                <section class="board" aria-labelledby="board-heading">
                    <h2 id="board-heading">Active jobs</h2>
                    <ul class="job-list">
                        @for (job of jobs(); track job.id) {
                            <li [class.selected]="job.id === activeJob().id" class="job-row">
                                <button type="button" (click)="focusJob(job.id)">
                                    <span class="job-id">{{ job.id }}</span>
                                    <span class="job-route">{{ job.route }}</span>
                                    <span class="pill {{ job.priority }}">{{ job.priority }}</span>
                                    <strong class="status">{{ job.status }}</strong>
                                </button>
                            </li>
                        }
                    </ul>
                </section>

                <aside class="detail" aria-labelledby="detail-heading">
                    <p class="eyebrow">{{ activeJob().technician }}</p>
                    <h2 id="detail-heading">{{ activeJob().route }}</h2>
                    <p class="summary">{{ activeJob().summary }}</p>

                    <label class="field">
                        Dispatch reference
                        <!-- Opted into snapshots via #dispatch-reference in safeValueSelectors. -->
                        <input
                            id="dispatch-reference"
                            [value]="dispatchReference()"
                            (input)="setDispatchReference($event)"
                        />
                    </label>

                    <p class="ack">{{ tools_ack.lastAcknowledgement() }}</p>

                    <!-- Sensitive region — never captured in a page snapshot. -->
                    <section class="internal" data-wp-nova-ignore>
                        <h3>Internal contact (private)</h3>
                        <p>On-call lead: 555-0142 — do not share with the agent.</p>
                    </section>
                </aside>
            </main>
        </div>
    `,
})
export class AppComponent {
    protected readonly tools_ack = inject(DispatchToolRegistration);

    protected readonly jobs = signal<Job[]>(INITIAL_JOBS);
    protected readonly activeJobId = signal<string>(INITIAL_JOBS[0]?.id ?? "");
    protected readonly dispatchReference = signal<string>("REF-SY-2026-318");
    protected readonly banner = signal<string>("Two crews rolling, one on site.");

    protected readonly activeJob = computed<Job>(() => {
        const id = this.activeJobId();
        return this.jobs().find((job) => job.id === id) ?? (INITIAL_JOBS[0] as Job);
    });

    protected readonly chatEnabled = computed(
        () => (import.meta.env.VITE_NOVA_PUBLIC_SURFACE_ID ?? "").trim().length > 0,
    );

    // Docs: Angular > Component Mount. Stable tool definitions passed to the
    // standalone component; it (re)registers on change and unregisters on destroy.
    protected readonly tools: ToolDefinition[] = [
        {
            name: "focus_job",
            description: "Focuses the dispatch board on a job and returns its details.",
            inputSchema: {
                type: "object",
                properties: { jobId: { type: "string" } },
                required: ["jobId"],
            },
            mutating: false,
            handler: (args) => {
                const jobId = String(args["jobId"] ?? "");
                const job = this.jobs().find((candidate) => candidate.id === jobId);
                if (!job) return { ok: false, reason: "Job not found." };
                this.activeJobId.set(job.id);
                return { ok: true, job };
            },
        },
        {
            name: "set_job_status",
            description: "Changes the status of a dispatch job on the board.",
            inputSchema: {
                type: "object",
                properties: {
                    jobId: { type: "string" },
                    status: {
                        type: "string",
                        enum: ["Queued", "En route", "On site", "Closed"],
                    },
                },
                required: ["jobId", "status"],
            },
            mutating: true,
            confirmationCopy: "Change this job's status?",
            handler: (args) => {
                const jobId = String(args["jobId"] ?? this.activeJobId());
                const status = readStatus(args["status"]);
                let updated: Job | undefined;
                this.jobs.update((current) =>
                    current.map((job) => {
                        if (job.id !== jobId) return job;
                        updated = { ...job, status };
                        return updated;
                    }),
                );
                if (!updated) return { ok: false, reason: "Job not found." };
                this.activeJobId.set(updated.id);
                return { ok: true, job: updated };
            },
        },
        {
            name: "post_dispatch_note",
            description: "Updates the visible control-desk banner with a short note.",
            inputSchema: {
                type: "object",
                properties: { message: { type: "string" } },
                required: ["message"],
            },
            mutating: true,
            confirmationCopy: "Post this dispatch note?",
            handler: (args) => {
                const message = String(args["message"] ?? "");
                this.banner.set(message);
                return { ok: true, message };
            },
        },
        {
            name: "get_board_snapshot",
            description: "Returns the dispatch data currently visible on the board.",
            inputSchema: { type: "object", properties: {} },
            mutating: false,
            handler: () => ({
                activeJob: this.activeJob(),
                jobs: this.jobs(),
                banner: this.banner(),
                dispatchReference: this.dispatchReference(),
            }),
        },
    ];

    constructor() {
        // Register the service-owned tool (docs: Angular > Service API).
        this.tools_ack.register();
    }

    protected focusJob(jobId: string): void {
        this.activeJobId.set(jobId);
    }

    protected setDispatchReference(event: Event): void {
        const target = event.target;
        if (target instanceof HTMLInputElement) this.dispatchReference.set(target.value);
    }
}

function readStatus(value: unknown): JobStatus {
    if (value === "Queued" || value === "En route" || value === "On site" || value === "Closed") {
        return value;
    }
    return "Queued";
}

// release-examples/react/src/App.tsx
import { NovaChatProvider, type NovaToolDefinition } from "@wp-nova/chat-sdk-react";
import { useMemo, useRef, useState } from "react";
import { CreateTicketTool } from "./CreateTicketTool";

// Aurora Helpdesk — a small support console that consumes the RELEASED
// @wp-nova/chat-sdk-react package from npm. The integration follows
// https://chat.wp-nova.ai docs/react: mount NovaChatProvider once near the app
// root, pass stable tools through the `tools` prop, register a feature-scoped
// tool with the useNovaTool hook, and gate mounting with `enabled`.

type Priority = "low" | "normal" | "high" | "urgent";

export interface Ticket {
    id: string;
    subject: string;
    customer: string;
    priority: Priority;
    queue: string;
    summary: string;
}

const initialTickets: Ticket[] = [
    {
        id: "AUR-4821",
        subject: "Checkout fails on saved card",
        customer: "Marlow Bakeries",
        priority: "high",
        queue: "Billing",
        summary: "Card on file is declined at the final step even though the bank approves it.",
    },
    {
        id: "AUR-4830",
        subject: "Export to CSV is missing columns",
        customer: "Northwind Labs",
        priority: "normal",
        queue: "Reporting",
        summary: "The weekly export dropped the owner and region columns after the last update.",
    },
    {
        id: "AUR-4845",
        subject: "SSO redirect loop",
        customer: "Cobalt Aerospace",
        priority: "urgent",
        queue: "Identity",
        summary: "After login the user bounces between the IdP and the app and never lands.",
    },
];

const DEFAULT_TICKET = initialTickets[0] as Ticket;

// Browser-safe config. Only VITE_* (public) values reach the bundle; the
// integration secret lives in the Vite token proxy (see vite.config.ts).
function readConfig() {
    return {
        publicSurfaceId: import.meta.env.VITE_NOVA_PUBLIC_SURFACE_ID ?? "",
        tokenEndpoint: "/api/nova-token",
        baseUrl: import.meta.env.VITE_NOVA_BASE_URL,
        title: "Aurora assistant",
        accent: "#5b5bd6",
        triggerColor: "#5b5bd6",
        triggerIconColor: "light" as const,
        // Opt this input's VALUE into page snapshots; field values are otherwise
        // default-deny. safeValueSelectors only affects value fields (input/select/
        // textarea) — plain visible text is already captured.
        safeValueSelectors: ["#case-reference"],
    };
}

export function App() {
    const [tickets, setTickets] = useState(initialTickets);
    const [activeId, setActiveId] = useState(DEFAULT_TICKET.id);
    const [caseReference, setCaseReference] = useState("CASE-2026-0142");
    const [banner, setBanner] = useState("Queue is healthy — 3 open tickets.");

    const config = useMemo(readConfig, []);
    const enabled = config.publicSurfaceId.trim().length > 0;

    const activeTicket = tickets.find((ticket) => ticket.id === activeId) ?? DEFAULT_TICKET;

    // The wrapper registers a tool once and keys re-registration on the tool's
    // content signature (name/description/schema/mutating/confirmationCopy), not
    // handler identity. So handlers must NOT close over render-scoped state — read
    // it through a ref that is refreshed every render instead.
    const liveRef = useRef({ tickets, activeTicket, banner, caseReference });
    liveRef.current = { tickets, activeTicket, banner, caseReference };

    // Stable tools live in the `tools` prop (docs: "Registering Tools with
    // Definitions"). Each handler mutates visible page state and returns
    // JSON-serializable data.
    const tools = useMemo<NovaToolDefinition[]>(
        () => [
            {
                name: "focus_ticket",
                description: "Focuses the console on a specific ticket and returns its details.",
                inputSchema: {
                    type: "object",
                    properties: { ticketId: { type: "string" } },
                    required: ["ticketId"],
                },
                mutating: false,
                handler: (args) => {
                    const ticketId = String(args.ticketId ?? "");
                    const ticket = liveRef.current.tickets.find(
                        (candidate) => candidate.id === ticketId,
                    );
                    if (!ticket) return { ok: false, reason: "Ticket not found." };
                    setActiveId(ticket.id);
                    return { ok: true, ticket };
                },
            },
            {
                name: "set_ticket_priority",
                description: "Changes the priority of a support ticket in the queue.",
                inputSchema: {
                    type: "object",
                    properties: {
                        ticketId: { type: "string" },
                        priority: {
                            type: "string",
                            enum: ["low", "normal", "high", "urgent"],
                        },
                    },
                    required: ["ticketId", "priority"],
                },
                mutating: true,
                confirmationCopy: "Change this ticket's priority?",
                handler: (args) => {
                    const ticketId = String(args.ticketId ?? liveRef.current.activeTicket.id);
                    const priority = readPriority(args.priority);
                    let updated: Ticket | undefined;
                    setTickets((current) =>
                        current.map((ticket) => {
                            if (ticket.id !== ticketId) return ticket;
                            updated = { ...ticket, priority };
                            return updated;
                        }),
                    );
                    if (!updated) return { ok: false, reason: "Ticket not found." };
                    setActiveId(updated.id);
                    return { ok: true, ticket: updated };
                },
            },
            {
                name: "post_status_banner",
                description: "Updates the visible status banner with a short operations note.",
                inputSchema: {
                    type: "object",
                    properties: { message: { type: "string" } },
                    required: ["message"],
                },
                mutating: true,
                confirmationCopy: "Post this status banner?",
                handler: (args) => {
                    const message = String(args.message ?? "");
                    setBanner(message);
                    return { ok: true, message };
                },
            },
            {
                name: "get_console_snapshot",
                description: "Returns the helpdesk data currently visible in the console.",
                inputSchema: { type: "object", properties: {} },
                mutating: false,
                handler: () => ({ ...liveRef.current }),
            },
        ],
        // Registered once; handlers read live state from liveRef, so this stays stable.
        [],
    );

    return (
        <NovaChatProvider config={config} enabled={enabled} tools={tools}>
            {/* useNovaTool belongs to a feature component and unregisters on unmount. */}
            <CreateTicketTool
                activeTicketId={activeTicket.id}
                onCreate={(ticket) => setTickets((current) => [ticket, ...current])}
            />

            <div className="app-shell">
                <header className="masthead">
                    <div>
                        <p className="eyebrow">Aurora Helpdesk</p>
                        <h1>Support console</h1>
                    </div>
                    <p className="banner" role="status">
                        {banner}
                    </p>
                </header>

                {!enabled && (
                    <p className="notice">
                        Set <code>VITE_NOVA_PUBLIC_SURFACE_ID</code> in <code>.env</code> to mount
                        the chat launcher.
                    </p>
                )}

                {/* data-ai-context is only captured from VISIBLE, in-viewport,
                    non-sensitive elements, so these render as a small context line. */}
                <p className="context">
                    <span data-ai-context="currentPageKind">helpdesk-console</span>
                    <span data-ai-context="activeTicketId">{activeTicket.id}</span>
                </p>

                <main className="layout">
                    <section className="queue" aria-labelledby="queue-heading">
                        <h2 id="queue-heading">Open tickets</h2>
                        <ul className="ticket-list">
                            {tickets.map((ticket) => (
                                <li
                                    key={ticket.id}
                                    className={
                                        ticket.id === activeTicket.id
                                            ? "ticket-row selected"
                                            : "ticket-row"
                                    }
                                >
                                    <button type="button" onClick={() => setActiveId(ticket.id)}>
                                        <span className="ticket-id">{ticket.id}</span>
                                        <span className="ticket-subject">{ticket.subject}</span>
                                        <span className={`pill ${ticket.priority}`}>
                                            {ticket.priority}
                                        </span>
                                    </button>
                                </li>
                            ))}
                        </ul>
                    </section>

                    <aside className="detail" aria-labelledby="detail-heading">
                        <p className="eyebrow">{activeTicket.queue} queue</p>
                        <h2 id="detail-heading">{activeTicket.subject}</h2>
                        <p className="customer">{activeTicket.customer}</p>
                        <p className="summary">{activeTicket.summary}</p>

                        <label className="field">
                            Case reference
                            {/* Opted into snapshots via #case-reference in safeValueSelectors. */}
                            <input
                                id="case-reference"
                                value={caseReference}
                                onChange={(event) => setCaseReference(event.target.value)}
                            />
                        </label>

                        {/* Sensitive region — never captured in a page snapshot. */}
                        <section className="internal" data-wp-nova-ignore>
                            <h3>Internal notes (private)</h3>
                            <p>Escalation contact: pat@aurora.example — do not share with the agent.</p>
                        </section>
                    </aside>
                </main>
            </div>
        </NovaChatProvider>
    );
}

function readPriority(value: unknown): Priority {
    if (value === "low" || value === "normal" || value === "high" || value === "urgent") {
        return value;
    }
    return "normal";
}
